# Generated by Django 4.1.4 on 2022-12-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sistem",
            fields=[
                (
                    "index",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("islemci", models.CharField(max_length=100)),
                ("ekran_karti", models.CharField(max_length=100)),
                ("ram", models.CharField(max_length=100)),
                ("depolama", models.CharField(max_length=100)),
                ("fiyat", models.CharField(max_length=100)),
                ("satici", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=300)),
                ("img", models.CharField(max_length=300)),
            ],
        ),
    ]
