# Generated by Django 4.1.4 on 2022-12-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sistemler", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sistem",
            old_name="index",
            new_name="id",
        ),
    ]
