# Generated by Django 4.1.4 on 2022-12-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sistemler", "0002_rename_index_sistem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sistem",
            name="fiyat",
            field=models.IntegerField(),
        ),
    ]
